spring.application.name=banktransaction
server.port =8081

# Connection Server Details
sqlserver.servername=localhost
sqlserver.portno=3306
sqlserver.userid=root
sqlserver.password=Venk@123
sqlserver.dbname=banktransaction




