companyid=KM3o6UtD1xB1cC5U/UFbKJPLeCFpgp1p3jwGpj1DmXYuQ34QA0HBoQ8t9juSiY+J
servername=1nEX9eN+Y4EaCNkzRipBQT2G3Ik8y2L+ECWuNyXXl8py8yaAIY0j1+QqrOXeQMjc
portno=bmgb+RZ2pqZTUbvQG+dbCaUsWuazA5FgkkEwEicw0iisz1ZqWED+Uaf/RaA8/5j8
userid=OvRilj7GO4FRyU6V/v5dOaXaSKD1U3aXq7AjV3lfbxFQm1eQa84BaItVu8aRkOOC
password=vp08K0sNAHb4+7an6/kjqKJ4+jWsNBJQiRNVsgS8UU8JQMlAawQLX3pleRdSt9Df

svnurl=xe/4xI3bobGKPQoRBOq4ri4J9aPOFNt8IPbtPiR2d6V3ojO42lm76H09N4LqtGvTsn7Kz5M/cvfI/BQwQCVmSaMdtNZT9Ba2Mwmsu5c9QXY=
destinationurl=gkKgfO41GjXrLDWVCon//Yr0dTXnmtVT4doB9M5jfY/73KsAjTGB80hTUP5MlXBj
svnuserid=+KUf+HYcmZXnv70ek3TG8NcqGXv9/8GSEh95GeCpaqEEyQXChTHgTLit8rlBNy+J
svnpassword=uUaJpHW3uGXOpuVsP8XARNRh8ZaUuIEpj94hErjgstBv7m0jYKoDks/+JRA1Ilmz
cron.backuptime=0 0 19 * * *
basedon.data=N
othersource.backupNeed=ZQZtbQhYCQeRN1Kr/KWQxotRn5EwPwV6+p7YWqsRzxflhzjYGnjNBYgvHH4UwVFz
othersource.pathDetails=mkUQuUMQHqL8a/niVX3ZFjjT/nM96Uc1DBGzSJmoLWVnklvnq9tp3kjuVKXrz1WbptMy/IgpA55xWeBDAbCe3OCwufk19PH647vevxWRzHw=


